<?php

/*---onefile------------------------------------------------------------

xml22 -  - parse XML file into an array with PHP

Version 0.3.0

Copyright (C) 2002 Ingo Schramm

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or (at
your option) any later version.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
USA

Overview:

This PHP4 code parses an XML document into a multidimensional
array. The parser recognizes almost all of XML, including entities and
notations. In addition many functions are provided to search and
edit the document, build a new one and write it back to a file. The
xml22 code is aimed to provide a functionality similar to the
Document Object Model in a procedural manner.

Documentation:

xml22.html, delivered with this package

or

http://code.ister.org

----------------------------------------------------------------------*/



